/* eslint-disable local/no-jsx-literals -- Operations copy is English-only. */
import Link from 'next/link';
import { createNotificationTemplate, processNotifications, retryNotification, testNotification, updateNotificationTemplate } from '../actions';
import { ActionMessage } from '../components/action-message';
import { ApiNotice } from '../components/api-notice';
import { TablePagination } from '../components/table-pagination';
import { fetchNotificationDeliveries, fetchNotificationTemplates } from '../lib/api';

export const dynamic = 'force-dynamic';

export default async function NotificationsPage({ searchParams }: { searchParams: Promise<{ page?: string; status?: string; q?: string; success?: string; error?: string }> }) {
  const params = await searchParams;
  const filters = { page: Math.max(1, Number(params.page) || 1), ...(params.status ? { status: params.status } : {}), ...(params.q ? { q: params.q } : {}) };
  const [templates, deliveries] = await Promise.all([fetchNotificationTemplates(), fetchNotificationDeliveries(filters)]);
  return <>
    <section className="page-heading"><div><p className="eyebrow">Customer communications</p><h1>Notifications</h1><p>Manage templates, delivery failures and queued customer messages.</p></div><form action={processNotifications}><button className="button button-primary">Process queue</button></form></section>
    <ActionMessage success={params.success} error={params.error} />
    <article className="panel section-gap"><header className="panel-header"><div><p className="eyebrow">New communication</p><h2>Create template</h2></div></header><form action={createNotificationTemplate} className="notification-create"><input name="event" placeholder="ORDER_CONFIRMED" required /><select name="channel"><option value="EMAIL">Email</option><option value="SMS">SMS</option><option value="PUSH">Push</option><option value="WHATSAPP">WhatsApp</option></select><input name="locale" defaultValue="en-GB" /><input name="subject" placeholder="Subject (email only)" /><textarea name="body" rows={5} placeholder="Hello {{firstName}}, your order is confirmed." required /><button className="button button-primary">Create template</button></form></article>
    <section className="admin-grid section-gap">
      <article className="panel"><header className="panel-header"><div><p className="eyebrow">Versioned content</p><h2>Templates</h2></div>{templates.ok && <span className="count-pill">{templates.data.length}</span>}</header>{!templates.ok ? <ApiNotice message={templates.error} /> : <div className="record-list">{templates.data.map(item => <details className="notification-template" key={item.id}><summary><span><strong>{item.event}</strong><small>{item.locale} · version {item.version}</small></span><span className="soft-badge">{item.channel}</span></summary><form action={updateNotificationTemplate} className="template-editor"><input type="hidden" name="id" value={item.id} /><input type="hidden" name="event" value={item.event} /><input type="hidden" name="channel" value={item.channel} /><input type="hidden" name="locale" value={item.locale} /><input name="subject" defaultValue={item.subject ?? ''} placeholder="Subject" /><textarea name="body" rows={7} defaultValue={item.body} required /><button className="button button-muted">Save new version</button></form><form action={testNotification} className="test-notification"><input type="hidden" name="id" value={item.id} /><input name="recipient" placeholder="Test recipient" required /><input name="data" defaultValue="{}" aria-label="Template data JSON" /><button className="button button-primary">Send test</button></form></details>)}</div>}</article>
      <article className="panel"><header className="panel-header"><div><p className="eyebrow">Delivery monitoring</p><h2>Delivery log</h2></div>{deliveries.ok && <span className="count-pill">{deliveries.data.total}</span>}</header><form action="/notifications" className="notification-filters"><input name="q" defaultValue={params.q} placeholder="Recipient or event" /><select name="status" defaultValue={params.status ?? ''}><option value="">All statuses</option><option value="QUEUED">Queued</option><option value="PROCESSING">Processing</option><option value="SENT">Sent</option><option value="DEAD_LETTER">Dead letter</option></select><button className="button button-muted">Filter</button>{(params.q || params.status) && <Link className="clear-link" href="/notifications">Clear</Link>}</form>{!deliveries.ok ? <ApiNotice message={deliveries.error} /> : deliveries.data.items.length ? <div className="record-list">{deliveries.data.items.map(item => <div className="record-row" key={item.id}><div><strong>{item.event} · {item.channel}</strong><small>{item.recipient} · {item.attempts} attempt(s){item.lastError ? ` · ${item.lastError}` : ''}</small></div><span className={`status-badge ${item.status === 'SENT' ? 'status-active' : item.status === 'DEAD_LETTER' ? 'status-down' : 'status-warn'}`}><span />{item.status.replaceAll('_', ' ')}</span>{item.status === 'DEAD_LETTER' && <form action={retryNotification}><input type="hidden" name="id" value={item.id} /><button className="text-action">Retry</button></form>}</div>)}</div> : <div className="empty-state compact-empty"><p>No matching deliveries.</p></div>}{deliveries.ok && <TablePagination basePath="/notifications" page={deliveries.data.page} pageCount={deliveries.data.pageCount} total={deliveries.data.total} params={{ ...(params.q ? { q: params.q } : {}), ...(params.status ? { status: params.status } : {}) }} />}</article>
    </section>
  </>;
}
