/* eslint-disable local/no-jsx-literals */
import { createNotificationTemplate, processNotifications, testNotification, updateNotificationTemplate } from '../actions';
import { ActionMessage } from '../components/action-message';
import { ApiNotice } from '../components/api-notice';
import { fetchNotificationDeliveries, fetchNotificationTemplates } from '../lib/api';
export const dynamic='force-dynamic';
export default async function NotificationsPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){
  const[p,t,d]=await Promise.all([searchParams,fetchNotificationTemplates(),fetchNotificationDeliveries()]);
  return <><section className="page-heading"><div><p className="eyebrow">Customer communications</p><h1>Notifications</h1><p>Create versioned email, SMS, push and WhatsApp templates, run tests, and process queued event messages.</p></div><form action={processNotifications}><button className="button button-primary">Process queue</button></form></section><ActionMessage success={p.success} error={p.error}/>
    <article className="panel section-gap"><header className="panel-header"><div><p className="eyebrow">New communication</p><h2>Create template</h2></div></header><form action={createNotificationTemplate} className="notification-create"><input name="event" placeholder="ORDER_CONFIRMED" required/><select name="channel"><option value="EMAIL">Email</option><option value="SMS">SMS</option><option value="PUSH">Push</option><option value="WHATSAPP">WhatsApp</option></select><input name="locale" defaultValue="en-GB"/><input name="subject" placeholder="Subject (email only)"/><textarea name="body" rows={5} placeholder="Hello {{firstName}}, your order is confirmed." required/><button className="button button-primary">Create template</button></form></article>
    <section className="admin-grid section-gap"><article className="panel"><header className="panel-header"><div><p className="eyebrow">Versioned content</p><h2>Templates</h2></div>{t.ok&&<span className="count-pill">{t.data.length}</span>}</header>{!t.ok?<ApiNotice message={t.error}/>:<div className="record-list">{t.data.map(item=><details className="notification-template" key={item.id}><summary><span><strong>{item.event}</strong><small>{item.locale} · version {item.version}</small></span><span className="soft-badge">{item.channel}</span></summary><form action={updateNotificationTemplate} className="template-editor"><input type="hidden" name="id" value={item.id}/><input type="hidden" name="event" value={item.event}/><input type="hidden" name="channel" value={item.channel}/><input type="hidden" name="locale" value={item.locale}/><input name="subject" defaultValue={item.subject??''} placeholder="Subject"/><textarea name="body" rows={7} defaultValue={item.body} required/><button className="button button-muted">Save new version</button></form><form action={testNotification} className="test-notification"><input type="hidden" name="id" value={item.id}/><input name="recipient" placeholder="Test recipient" required/><input name="data" defaultValue="{}" aria-label="Template data JSON"/><button className="button button-primary">Send test</button></form></details>)}</div>}</article>
      <article className="panel"><header className="panel-header"><div><p className="eyebrow">Delivery monitoring</p><h2>Delivery log</h2></div>{d.ok&&<span className="count-pill">{d.data.length}</span>}</header>{!d.ok?<ApiNotice message={d.error}/>:d.data.length?<div className="record-list">{d.data.map(item=><div className="record-row" key={item.id}><div><strong>{item.event} · {item.channel}</strong><small>{item.recipient} · {item.attempts} attempt(s){item.lastError?` · ${item.lastError}`:''}</small></div><span className={`status-badge ${item.status==='SENT'?'status-active':item.status==='FAILED'?'status-down':'status-warn'}`}><span/>{item.status}</span></div>)}</div>:<div className="empty-state compact-empty"><p>No deliveries have been queued.</p></div>}</article></section>
  </>;
}
