'use client';
import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { browserApi, money } from '../../lib/store-api';

interface CartItem { id: string; productId: string; name: string; quantity: number; currentPriceMinor: string; lineTotalMinor: string; availableStock: number; ageRestriction: number; substitutionPreference: string }
interface Cart { groups: Array<{ category: 'GROCERY' | 'ALCOHOL'; items: CartItem[]; subtotalMinor: string }>; totals: { subtotalMinor: string; discountMinor: string; taxMinor: string; grandTotalMinor: string }; currency: string; requiresAgeVerification: boolean; changes: Array<{ type: string }> }
export default function CartPage() {
  const [cart, setCart] = useState<Cart | null>(null); const [error, setError] = useState(''); const [coupon, setCoupon] = useState('');
  const load = useCallback(async () => { try { setCart(await browserApi<Cart>('/api/v1/cart')); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Basket unavailable'); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function change(item: CartItem, quantity: number) { try { setCart(await browserApi<Cart>(`/api/v1/cart/items/${item.id}`, quantity < 1 ? { method: 'DELETE' } : { method: 'PATCH', body: JSON.stringify({ quantity }) })); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not update basket'); } }
  async function applyCoupon() { try { setCart(await browserApi<Cart>('/api/v1/cart/coupon', { method: 'POST', body: JSON.stringify({ code: coupon }) })); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Coupon is unavailable'); } }
  if (error && !cart) return <main className="section"><div className="error-state"><h1>Basket unavailable</h1><p>{error}</p><button className="button" onClick={load}>Try again</button></div></main>;
  if (!cart) return <main className="section"><div className="skeleton">Loading your basket…</div></main>;
  const count = cart.groups.reduce((total, group) => total + group.items.length, 0);
  if (!count) return <main className="section"><div className="empty-state"><h1>Your basket is empty</h1><p>Browse the live catalogue and add something good.</p><Link className="button" href="/category/all">Start shopping</Link></div></main>;
  return <main className="section"><p className="eyebrow">Your order</p><h1>Basket</h1>{cart.changes.length > 0 && <div className="notice" role="status">We refreshed {cart.changes.length} basket {cart.changes.length === 1 ? 'detail' : 'details'}. Please review before checkout.</div>}<div className="cart-layout"><div>{cart.groups.map((group) => group.items.length > 0 && <section className={`cart-group ${group.category.toLowerCase()}`} key={group.category}><div className="cart-group-title"><h2>{group.category === 'GROCERY' ? 'Groceries' : 'Alcohol · 18+'}</h2><strong>{money(group.subtotalMinor, cart.currency)}</strong></div>{group.items.map((item) => <article className="cart-item" key={item.id}><div className="mini-art">{group.category === 'ALCOHOL' ? '18+' : item.name.slice(0, 1)}</div><div><Link href={`/product/${item.productId}`}><strong>{item.name}</strong></Link><p>{money(item.currentPriceMinor, cart.currency)} each</p><label>Substitution <select defaultValue={item.substitutionPreference} onChange={(event) => void browserApi(`/api/v1/cart/items/${item.id}/substitution-preference`, { method: 'POST', body: JSON.stringify({ preference: event.target.value }) })}><option value="SIMILAR">Similar item</option><option value="NONE">Do not substitute</option></select></label></div><div className="quantity"><button onClick={() => void change(item, item.quantity - 1)} aria-label={`Reduce ${item.name}`}>−</button><output>{item.quantity}</output><button onClick={() => void change(item, item.quantity + 1)} aria-label={`Add another ${item.name}`}>+</button></div><strong>{money(item.lineTotalMinor, cart.currency)}</strong></article>)}</section>)}</div><aside className="order-summary"><h2>Order summary</h2><dl><div><dt>Subtotal</dt><dd>{money(cart.totals.subtotalMinor, cart.currency)}</dd></div><div><dt>Discount</dt><dd>−{money(cart.totals.discountMinor, cart.currency)}</dd></div><div><dt>VAT included</dt><dd>{money(cart.totals.taxMinor, cart.currency)}</dd></div><div className="total"><dt>Total</dt><dd>{money(cart.totals.grandTotalMinor, cart.currency)}</dd></div></dl><div className="coupon-row"><input value={coupon} onChange={(event) => setCoupon(event.target.value)} placeholder="Coupon code" /><button onClick={applyCoupon}>Apply</button></div>{cart.requiresAgeVerification && <div className="compliance-note"><strong>Challenge 25</strong><p>Age verification is required and valid photo ID may be requested on delivery.</p></div>}<Link className="button full" href="/checkout">Continue to checkout</Link>{error && <p className="form-error" role="alert">{error}</p>}</aside></div></main>;
}
