/* eslint-disable local/no-jsx-literals */
import { toggleCustomer } from '../actions';
import Link from 'next/link';
import { ActionMessage } from '../components/action-message';
import { ApiNotice } from '../components/api-notice';
import { Currency } from '../components/currency';
import { fetchCustomers } from '../lib/api';
export const dynamic = 'force-dynamic';
export default async function CustomersPage({searchParams}:{searchParams:Promise<{q?:string;success?:string;error?:string}>}) { const params=await searchParams; const result=await fetchCustomers(params.q); return <><section className="page-heading"><div><p className="eyebrow">CRM</p><h1>Customers</h1><p>Live customer accounts, order counts, spend and account status.</p></div></section><ActionMessage success={params.success} error={params.error}/><article className="panel"><form action="/customers" className="catalog-toolbar"><input name="q" defaultValue={params.q} placeholder="Search email or name"/><button className="button button-primary">Search</button></form>{!result.ok?<ApiNotice message={result.error}/>:<div className="table-wrap"><table><thead><tr><th>Customer</th><th>Contact</th><th>Orders</th><th>Spend</th><th>Status</th><th/></tr></thead><tbody>{result.data.map(customer=><tr key={customer.id}><td><Link href={`/customers/${customer.id}`}><strong>{customer.firstName} {customer.lastName}</strong></Link><small className="cell-subtext">Joined {new Date(customer.createdAt).toLocaleDateString('en-GB')}</small></td><td>{customer.email}<small className="cell-subtext">{customer.phone??'No phone'}</small></td><td>{customer.orderCount}</td><td><Currency minor={customer.spendMinor}/></td><td><span className={`status-badge ${customer.active?'status-active':'status-down'}`}><span />{customer.active?'Active':'Disabled'}</span></td><td><Link className="text-action" href={`/customers/${customer.id}`}>View</Link><form action={toggleCustomer}><input type="hidden" name="id" value={customer.id}/><input type="hidden" name="active" value={String(customer.active)}/><button className="text-action" type="submit">{customer.active?'Disable':'Enable'}</button></form></td></tr>)}</tbody></table></div>}</article></>; }
