/* eslint-disable local/no-jsx-literals */
import { createBanner, createContentBlock, saveCmsPage, toggleBanner } from '../actions';
import { ActionMessage } from '../components/action-message';
import { ApiNotice } from '../components/api-notice';
import { fetchContent } from '../lib/api';
export const dynamic='force-dynamic';
export default async function ContentPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){
  const [query,result]=await Promise.all([searchParams,fetchContent()]);
  return <><section className="page-heading"><div><p className="eyebrow">Storefront publishing</p><h1>Banners & CMS</h1><p>Create scheduled homepage merchandising and publish the store’s legal and policy pages.</p></div></section><ActionMessage success={query.success} error={query.error}/>{!result.ok?<ApiNotice message={result.error}/>:<>
    <section className="admin-grid">
      <article className="panel"><header className="panel-header"><div><p className="eyebrow">Homepage media</p><h2>Banners</h2></div><span className="count-pill">{result.data.banners.length}</span></header><form action={createBanner} className="content-form"><input name="title" placeholder="Banner title" required/><input name="subtitle" placeholder="Subtitle"/><input name="imageUrl" type="url" placeholder="Desktop image URL" required/><input name="mobileImageUrl" type="url" placeholder="Mobile image URL"/><input name="linkUrl" type="url" placeholder="Destination URL"/><input name="position" type="number" min="0" defaultValue="0"/><label>Starts<input name="startsAt" type="datetime-local"/></label><label>Ends<input name="endsAt" type="datetime-local"/></label><button className="button button-primary">Create banner</button></form><div className="record-list">{result.data.banners.map(item=><div className="record-row" key={item.id}><div><strong>{item.title}</strong><small>{item.subtitle??item.imageUrl}</small></div><span className={`status-badge ${item.active?'status-active':'status-down'}`}><span/>{item.active?'Active':'Inactive'}</span><form action={toggleBanner}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="active" value={String(item.active)}/><button className="text-action">{item.active?'Pause':'Enable'}</button></form></div>)}</div></article>
      <article className="panel"><header className="panel-header"><div><p className="eyebrow">Homepage layout</p><h2>Content blocks</h2></div><span className="count-pill">{result.data.blocks.length}</span></header><form action={createContentBlock} className="content-form"><select name="type"><option value="FEATURED_PRODUCTS">Featured products</option><option value="CATEGORY_TILES">Category tiles</option><option value="PROMO_BLOCK">Promotion block</option></select><input name="title" placeholder="Block title"/><input name="position" type="number" min="0" defaultValue="0"/><textarea className="wide-field" name="content" rows={5} defaultValue="{}" aria-label="Block JSON"/><button className="button button-primary">Add block</button></form><div className="record-list">{result.data.blocks.map(item=><div className="record-row" key={item.id}><div><strong>{item.title??item.type.replaceAll('_',' ')}</strong><small>{item.type.replaceAll('_',' ')}</small></div><span className="soft-badge">Position {item.position}</span></div>)}</div></article>
    </section>
    <article className="panel section-gap"><header className="panel-header"><div><p className="eyebrow">Policies</p><h2>Legal & service pages</h2><p>Saving the same page type and locale updates that page.</p></div></header><form action={saveCmsPage} className="cms-page-form"><select name="type"><option value="TERMS">Terms</option><option value="PRIVACY">Privacy</option><option value="COOKIE">Cookie policy</option><option value="RETURNS">Returns</option><option value="ALCOHOL_POLICY">Alcohol policy</option><option value="DELIVERY_POLICY">Delivery policy</option></select><input name="locale" defaultValue="en-GB"/><input name="title" placeholder="Page title" required/><label className="inline-checkbox"><input name="published" type="checkbox"/> Publish immediately</label><textarea name="content" rows={12} placeholder="Page content" required/><button className="button button-primary">Save page</button></form><div className="record-list">{result.data.pages.map(item=><div className="record-row" key={item.id}><div><strong>{item.title}</strong><small>{item.type.replaceAll('_',' ')} · {item.locale} · updated {new Date(item.updatedAt).toLocaleDateString('en-GB')}</small></div><span className={`status-badge ${item.published?'status-active':'status-warn'}`}><span/>{item.published?'Published':'Draft'}</span></div>)}</div></article>
  </>}</>;
}
