import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
type Entry = { licenses?: string };
const raw = execFileSync('pnpm', ['exec', 'license-checker-rseidelsohn', '--json', '--production'], { encoding: 'utf8' });
const entries = JSON.parse(raw) as Record<string, Entry>;
const denied = /(?:^|\s)(?:AGPL|GPL|SSPL|UNKNOWN)/i;
const bad = Object.entries(entries).filter(([, value]) => denied.test(value.licenses ?? 'UNKNOWN'));
const rows = Object.entries(entries).sort(([a], [b]) => a.localeCompare(b)).map(([name, value]) => `| ${name} | ${value.licenses ?? 'Unknown'} |`);
writeFileSync('docs/THIRD_PARTY_LICENSES.md', `# Third-party licences\n\nGenerated by \`pnpm licenses:audit\`.\n\n| Package | Licence |\n|---|---|\n${rows.join('\n')}\n`);
if (bad.length) { console.error(`Disallowed or unknown licences: ${bad.map(([name]) => name).join(', ')}`); process.exit(1); }
