import { BadRequestException, Injectable } from '@nestjs/common';
import { parse } from 'csv-parse';
import ExcelJS from 'exceljs';
import { Prisma } from '@prisma/client';
import { z } from 'zod';
import { TenantScopedPrismaService } from '../../common/database/tenant-scoped.service';
import { TenantContext } from '../../common/tenancy/tenant-context';

const rowSchema = z.object({ sku: z.string().min(1), slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), name: z.string().min(1), description: z.string().min(1), categorySlug: z.string().min(1), priceMinor: z.string().regex(/^\d+$/), vatRateBps: z.coerce.number().int().min(0).max(10000), restrictionReason: z.enum(['NONE', 'ALCOHOL', 'RETAILER_POLICY']), ageRestriction: z.coerce.number().int().min(0).max(100), abv: z.preprocess((value) => value === '' || value === undefined ? null : value, z.string().regex(/^(?:100(?:\.0{1,2})?|\d{1,2}(?:\.\d{1,2})?)$/).nullable()) });
type ImportRow = z.infer<typeof rowSchema>;
export type DuplicatePolicy = 'skip' | 'update' | 'fail';
interface RowError { rowNumber: number; field?: string; code: string; message: string; input: Record<string, unknown>; }

@Injectable()
export class CatalogImportService {
  constructor(private readonly db: TenantScopedPrismaService) {}
  async execute(file: Buffer, filename: string, duplicatePolicy: DuplicatePolicy, dryRun: boolean, createdById: string) {
    if (!['skip', 'update', 'fail'].includes(duplicatePolicy)) throw new BadRequestException('Duplicate policy is invalid');
    const tenantId = TenantContext.requireTenantId(); const job = await this.db.client.importJob.create({ data: { tenantId, type: 'CATALOG', status: 'VALIDATING', duplicatePolicy, dryRun, sourceFilename: filename, createdById } });
    const rawRows = await this.readRows(file); const valid: Array<{ rowNumber: number; value: ImportRow }> = []; const errors: RowError[] = [];
    rawRows.forEach((input, index) => { const result = rowSchema.safeParse(input); if (result.success) valid.push({ rowNumber: index + 2, value: result.data }); else for (const issue of result.error.issues) errors.push({ rowNumber: index + 2, ...(issue.path[0] ? { field: String(issue.path[0]) } : {}), code: issue.code, message: issue.message, input }); });
    const categories = await this.db.client.category.findMany({ where: { slug: { in: [...new Set(valid.map((row) => row.value.categorySlug))] } } }); const bySlug = new Map(categories.map((category) => [category.slug, category.id]));
    for (const row of valid) if (!bySlug.has(row.value.categorySlug)) errors.push({ rowNumber: row.rowNumber, field: 'categorySlug', code: 'UNKNOWN_CATEGORY', message: 'Category does not exist', input: row.value });
    const existing = await this.db.client.product.findMany({ where: { sku: { in: valid.map((row) => row.value.sku) } }, select: { sku: true } }); const duplicates = new Set(existing.map((product) => product.sku)); if (duplicatePolicy === 'fail') for (const row of valid) if (duplicates.has(row.value.sku)) errors.push({ rowNumber: row.rowNumber, field: 'sku', code: 'DUPLICATE_SKU', message: 'SKU already exists', input: row.value });
    if (errors.length > 0) { await this.db.transaction(async (tx) => { await tx.importError.createMany({ data: errors.map((error) => ({ tenantId, importJobId: job.id, rowNumber: error.rowNumber, field: error.field ?? null, code: error.code, message: error.message, input: error.input as Prisma.InputJsonObject })) }); await tx.importJob.update({ where: { id: job.id, tenantId }, data: { status: 'FAILED', totalRows: rawRows.length, validRows: valid.length, invalidRows: errors.length } }); }); return { jobId: job.id, applied: 0, errors }; }
    const changes = valid.filter((row) => !(duplicatePolicy === 'skip' && duplicates.has(row.value.sku))).map((row) => ({ sku: row.value.sku, operation: duplicates.has(row.value.sku) ? 'update' : 'create' }));
    if (dryRun) { await this.db.client.importJob.update({ where: { id: job.id }, data: { status: 'READY', totalRows: rawRows.length, validRows: valid.length, result: { changes } } }); return { jobId: job.id, applied: 0, changes }; }
    await this.db.transaction(async (tx) => { for (const row of valid) { if (duplicatePolicy === 'skip' && duplicates.has(row.value.sku)) continue; const data = this.productData(row.value, bySlug.get(row.value.categorySlug) as string, tenantId); await tx.product.upsert({ where: { tenantId_sku: { tenantId, sku: row.value.sku } }, create: data, update: data }); } await tx.importJob.update({ where: { id: job.id, tenantId }, data: { status: 'COMPLETE', totalRows: rawRows.length, validRows: valid.length, result: { changes } } }); await tx.auditLog.create({ data: { tenantId, actorId: createdById, actorType: 'USER', action: 'CATALOG_IMPORT', entity: 'ImportJob', entityId: job.id, after: { rows: valid.length, duplicatePolicy }, requestId: TenantContext.get()?.requestId ?? job.id } }); });
    return { jobId: job.id, applied: changes.length, changes };
  }
  async errorReport(jobId: string): Promise<string> { const errors = await this.db.client.importError.findMany({ where: { importJobId: jobId }, orderBy: { rowNumber: 'asc' } }); const escape = (value: string) => `"${value.replaceAll('"', '""')}"`; return ['row,field,code,message', ...errors.map((error) => [error.rowNumber, escape(error.field ?? ''), escape(error.code), escape(error.message)].join(','))].join('\n'); }
  private async readRows(file: Buffer): Promise<Record<string, unknown>[]> { if (file.length > 25 * 1024 * 1024) throw new BadRequestException('Import file exceeds 25 MB'); if (file.subarray(0, 4).equals(Buffer.from([0x50, 0x4b, 0x03, 0x04]))) { const workbook = new ExcelJS.Workbook(); await workbook.xlsx.load(file as never); const sheet = workbook.worksheets[0]; if (!sheet) return []; const headers = (sheet.getRow(1).values as unknown[]).slice(1).map(String); const rows: Record<string, unknown>[] = []; sheet.eachRow((row, rowNumber) => { if (rowNumber === 1) return; const values = (row.values as unknown[]).slice(1); rows.push(Object.fromEntries(headers.map((header, index) => [header, values[index] ?? '']))); }); return rows; } const rows: Record<string, unknown>[] = []; const parser = parse(file, { columns: true, bom: true, skip_empty_lines: true, trim: true }); for await (const row of parser) rows.push(row as Record<string, unknown>); return rows; }
  private productData(row: ImportRow, categoryId: string, tenantId: string): Prisma.ProductUncheckedCreateInput { const isAlcohol = row.restrictionReason === 'ALCOHOL'; return { tenantId, categoryId, sku: row.sku, slug: row.slug, name: row.name, description: row.description, status: 'ACTIVE', priceMinor: BigInt(row.priceMinor), currency: 'GBP', vatRateBps: row.vatRateBps, pricingMode: 'UNIT', isAlcohol, abv: row.abv ? new Prisma.Decimal(row.abv) : null, ageRestriction: row.ageRestriction, restrictionReason: row.restrictionReason, returnPolicy: isAlcohol ? 'AGE_RESTRICTED_RESTRICTED' : 'STANDARD_14_DAY', unitPriceDisplay: 'each', hfssStatus: 'NOT_IN_SCOPE', dietaryTags: [], allergens: [], countryOfOrigin: 'GB', storageType: 'AMBIENT' }; }
}
