/* eslint-disable local/no-jsx-literals */
import { ApiNotice } from '../components/api-notice';
import { Currency } from '../components/currency';
import { fetchCouponReport, fetchCustomerReport, fetchProductReport, fetchSalesReport } from '../lib/api';
export const dynamic = 'force-dynamic';
export default async function ReportsPage() {
  const [sales, customers, products, coupons] = await Promise.all([fetchSalesReport(), fetchCustomerReport(), fetchProductReport(), fetchCouponReport()]);
  return <><section className="page-heading"><div><p className="eyebrow">Business intelligence</p><h1>Reports</h1><p>Real order queries count mixed baskets once and split line revenue by grocery and alcohol.</p></div></section>{!sales.ok ? <ApiNotice message={sales.error} /> : <section className="metric-grid"><article className="metric-card"><div><p>Orders</p><strong>{sales.data.orders}</strong></div></article><article className="metric-card"><div><p>Total revenue</p><strong><Currency minor={sales.data.totalRevenueMinor}/></strong></div></article><article className="metric-card"><div><p>Grocery revenue</p><strong><Currency minor={sales.data.groceryRevenueMinor}/></strong></div></article><article className="metric-card"><div><p>Alcohol revenue</p><strong><Currency minor={sales.data.alcoholRevenueMinor}/></strong></div></article></section>}<section className="admin-grid"><article className="panel"><h2>Top products</h2>{products.ok ? <div className="table-wrap"><table><thead><tr><th>Product</th><th>Units</th><th>Revenue</th></tr></thead><tbody>{products.data.slice(0,20).map(row=><tr key={row.productId}><td><strong>{row.name}</strong><small className="cell-subtext">{row.sku}</small></td><td>{row.units}</td><td><Currency minor={row.revenueMinor}/></td></tr>)}</tbody></table></div>:<ApiNotice message={products.error}/>}</article><article className="panel"><h2>Customer & coupon usage</h2>{customers.ok && <p><strong>{customers.data.customers}</strong> purchasing customers · <strong>{customers.data.repeatCustomers}</strong> repeat</p>}{coupons.ok ? <div className="record-list">{coupons.data.map(row=><div className="record-row" key={row.couponId}><strong>{row.code}</strong><span>{row.uses} uses · <Currency minor={row.discountMinor}/></span></div>)}</div>:<ApiNotice message={coupons.error}/>}</article></section></>;
}
